### ISSUE TITLE
Installing in Program Files

### ISSUE THREAD

**Issue by sharkykh** [SickRage/SickRageInstaller#12]
### Copied from https://github.com/VinceVal/SickRageInstaller/issues/30
> I did not want to clutter my c drive, so I tried installing to `C:\Program Files\SickRage`. That did not work. I looked for the sickrage.py file, and it was nowhere in the directory structure.
> 
> A subsequent install to `C:\SickRage` did work, so my guess is that the current git setup does not work well with spaces in the path.

----

* **Unverified:** If the install path contains a space, the installation fails or doesn't install correctly.

**Comment by tinel-c** [comment]
Just tried to install today. And it does not bring the syckrage.py only does the python and git install.

**Comment by githubhermit** [comment]
Just tried installing and the Data folder is completely empty.
OS: Win 10
![er](https://user-images.githubusercontent.com/40477486/46559339-136c3480-c8be-11e8-8099-34ac4d81b6c0.JPG)
