### ISSUE TITLE
torrentday searching and dowloading not working

### ISSUE THREAD

**Issue by DeathlyKnife** [SickRage/SickRageInstaller#6]
### Steps to reproduce:
1. add movie to list
2. search

### Information:
Movie(s) I have this with: all of them on torrentday
Quality of the movie being searched: all of the posible ones
Providers I use: torrentday.com
Version of CouchPotato: desktop: 3.0.1
Running on:windows 10

### Logs:
```
04-08 17:15:19 ERROR [edia._base.providers.base] Failed to parsing TorrentDay: Traceback (most recent call last):
  File "C:\Users\TheDeathlyKnife\AppData\Roaming\CouchPotato\application\CouchPotato-3.0.1.win32\couchpotato\core\media\_base\providers\base.py", line 83, in getJsonData
  File "json\__init__.pyc", line 338, in loads
  File "json\decoder.pyc", line 366, in decode
  File "json\decoder.pyc", line 384, in raw_decode
ValueError: No JSON object could be decoded
 
```
I use sickrage for series and that works with torrenday and they ask for this.
Cookies (________________)
example: uid=1234;pass=567845439634987
note: uid and pass are not your username/password.
use DevTools or Firebug to get these values after logging in on your browser.

**Comment by sharkykh** [comment]
I think you got this wrong...
This is the SickRage installer, not CouchPotato.

**Comment by DeathlyKnife** [comment]
im so sorry wrong thing i will get on it on there website excuse me
